const activateBtn=document.getElementById("activateBtn"),
statusDot=document.getElementById("statusDot"),
statusText=document.getElementById("statusText"),
voiceOverlay=document.getElementById("voiceOverlay"),
voiceText=document.getElementById("voiceText"),
systemTime=document.getElementById("systemTime");
let history=[],isSpeaking=!1,mediaRecorder=null,audioChunks=[],micStream=null,recording=!1;
function updateTime(){const n=new Date;systemTime.textContent=String(n.getHours()).padStart(2,"0")+":"+String(n.getMinutes()).padStart(2,"0")+":"+String(n.getSeconds()).padStart(2,"0")}
updateTime();setInterval(updateTime,1e3);
async function checkHealth(){try{const r=await fetch("/api/health"),d=await r.json(),o="ok"===d.status;statusDot.classList.toggle("off",!o),statusText.textContent=o?"ONLINE":"OFFLINE"}catch{statusText.textContent="OFFLINE",statusDot.classList.add("off")}}
checkHealth();setInterval(checkHealth,15e3);
function showOverlay(t){voiceText.textContent=t,voiceOverlay.classList.add("on")}
function hideOverlay(){voiceOverlay.classList.remove("on")}
async function toggleMic(){if(recording)return stopRecording();if(isSpeaking&&window.speechSynthesis.cancel(),isSpeaking=!1,try{micStream=await navigator.mediaDevices.getUserMedia({audio:!0}),audioChunks=[];let e="";for(const t of["audio/webm;codecs=opus","audio/webm","audio/mp4"])MediaRecorder.isTypeSupported(t)&&(e=t);mediaRecorder=new MediaRecorder(micStream,e?{mimeType:e}:{}),mediaRecorder.ondataavailable=e=>{e.data&&e.data.size>0&&audioChunks.push(e.data)},mediaRecorder.onstop=async()=>{cleanupMic(),0===audioChunks.length?(hideOverlay(),statusText.textContent="NO AUDIO"):await processAudio(new Blob(audioChunks,{type:mediaRecorder.mimeType||"audio/webm"}))},mediaRecorder.onerror=()=>{cleanupMic(),hideOverlay(),statusText.textContent="ERROR"},mediaRecorder.start(200),recording=!0,activateBtn.classList.add("on"),activateBtn.textContent="PO DËGJOJ...",showOverlay("PO DËGJOJ..."),statusText.textContent="PO DËGJOJ...",setTimeout(()=>{recording&&mediaRecorder&&"recording"===mediaRecorder.state&&mediaRecorder.stop()},1e4)}catch(e){console.error("Mic error:",e),statusText.textContent="MIKROFON I REFUZUAR",hideOverlay()}}
function stopRecording(){mediaRecorder&&"recording"===mediaRecorder.state?mediaRecorder.stop():(cleanupMic(),hideOverlay())}
function cleanupMic(){recording=!1,micStream&&(micStream.getTracks().forEach(e=>e.stop()),micStream=null),activateBtn.classList.remove("on"),activateBtn.textContent="AKTIVIZO JARVIS"}
async function processAudio(e){showOverlay("PO PERKTHEJ..."),statusText.textContent="PO PERKTHEJ...";const t=new FormData;t.append("audio",e,"recording.webm");try{const r=await fetch("/api/speech-to-text",{method:"POST",body:t}),d=await r.json();hideOverlay();d.text&&d.text.trim()?sendMessage(d.text.trim()):(statusText.textContent="NUK DËGJOVA",await speak("Nuk degjova asgje. Provo perseri."))}catch(e){console.error("STT error:",e),hideOverlay(),statusText.textContent="GABIM"}}
async function speak(t){if(!t)return;isSpeaking=!0,statusText.textContent="PO FLAS...";try{const r=await fetch("/api/text-to-speech",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({text:t})}),d=await r.json();if(d.audio&&d.audio.length>0){const s=new Uint8Array(d.audio),b=new Blob([s],{type:"audio/mpeg"}),u=URL.createObjectURL(b),a=new Audio(u);a.onend=()=>{isSpeaking=!1,URL.revokeObjectURL(u),statusText.textContent="ONLINE"},a.onerror=()=>{isSpeaking=!1,URL.revokeObjectURL(u),fallbackSpeak(t)},await a.play()}else fallbackSpeak(t)}catch{fallbackSpeak(t)}}
function fallbackSpeak(t){if(!("speechSynthesis"in window))return isSpeaking=!1,void(statusText.textContent="ONLINE");window.speechSynthesis.cancel();const e=new SpeechSynthesisUtterance(t.replace(/[*_`#]/g,""));e.lang="sq-AL",e.onend=()=>{isSpeaking=!1,statusText.textContent="ONLINE"},window.speechSynthesis.speak(e)}
async function sendMessage(t){if(!t.trim())return;history.push({role:"user",content:t}),statusText.textContent="PO MENDOJ...",showOverlay("PO MENDOJ...");try{const r=await fetch("/api/chat",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({message:t,history:history.slice(-20)})}),d=await r.json();hideOverlay();const p=d.reply||"Gabim.";history.push({role:"assistant",content:p}),await speak(p)}catch{hideOverlay(),statusText.textContent="GABIM",await speak("Gabim lidhjeje.")}}
activateBtn.addEventListener("click",toggleMic);
voiceOverlay.addEventListener("click",e=>{"overlayClose"===e.target.id&&recording&&stopRecording()});
