const chatArea=document.getElementById("chatArea"),userInput=document.getElementById("userInput"),
sendBtn=document.getElementById("sendBtn"),statusDot=document.getElementById("statusDot"),
statusText=document.getElementById("statusText"),voiceOverlay=document.getElementById("voiceOverlay"),
voiceText=document.getElementById("voiceText"),systemTime=document.getElementById("systemTime"),
wakeBtn=document.getElementById("mic"),chatPanel=document.getElementById("chat"),
chatToggle=document.getElementById("chatToggle");
let history=[],isSpeaking=!1,mediaRecorder=null,audioChunks=[],micStream=null,recording=!1;
function updateTime(){const n=new Date;systemTime.textContent=String(n.getHours()).padStart(2,"0")+":"+String(n.getMinutes()).padStart(2,"0")+":"+String(n.getSeconds()).padStart(2,"0")}
updateTime();setInterval(updateTime,1e3);
async function checkHealth(){try{const r=await fetch("/api/health"),d=await r.json(),o="ok"===d.status;statusDot.classList.toggle("off",!o),statusText.textContent=o?"ONLINE":"OFFLINE"}catch{statusText.textContent="OFFLINE",statusDot.classList.add("off")}}
checkHealth();setInterval(checkHealth,15e3);
chatToggle.addEventListener("click",()=>chatPanel.classList.toggle("hide"));
function showOverlay(t){voiceText.textContent=t,voiceOverlay.classList.add("on")}
function hideOverlay(){voiceOverlay.classList.remove("on")}
async function toggleMic(){if(recording)return stopRecording();if(isSpeaking&&window.speechSynthesis.cancel(),isSpeaking=!1,try{micStream=await navigator.mediaDevices.getUserMedia({audio:!0}),audioChunks=[];let e="";for(const t of["audio/webm;codecs=opus","audio/webm","audio/mp4"])MediaRecorder.isTypeSupported(t)&&(e=t);mediaRecorder=new MediaRecorder(micStream,e?{mimeType:e}:{}),mediaRecorder.ondataavailable=e=>{e.data&&e.data.size>0&&audioChunks.push(e.data)},mediaRecorder.onstop=async()=>{cleanupMic(),0===audioChunks.length?(hideOverlay(),statusText.textContent="NO AUDIO"):await processAudio(new Blob(audioChunks,{type:mediaRecorder.mimeType||"audio/webm"}))},mediaRecorder.onerror=()=>{cleanupMic(),hideOverlay(),statusText.textContent="ERROR"},mediaRecorder.start(200),recording=!0,wakeBtn.classList.add("on"),showOverlay("PO DËGJOJ..."),statusText.textContent="PO DËGJOJ...",setTimeout(()=>{recording&&mediaRecorder&&"recording"===mediaRecorder.state&&mediaRecorder.stop()},1e4)}catch(e){console.error("Mic error:",e),statusText.textContent="MIKROFON I REFUZUAR",hideOverlay()}}
function stopRecording(){mediaRecorder&&"recording"===mediaRecorder.state?mediaRecorder.stop():(cleanupMic(),hideOverlay())}
function cleanupMic(){recording=!1,micStream&&(micStream.getTracks().forEach(e=>e.stop()),micStream=null),wakeBtn.classList.remove("on")}
async function processAudio(e){showOverlay("PO PERKTHEJ..."),statusText.textContent="PO PERKTHEJ...";const t=new FormData;t.append("audio",e,"recording.webm");try{const r=await fetch("/api/speech-to-text",{method:"POST",body:t}),d=await r.json();hideOverlay();d.text&&d.text.trim()?sendMessage(d.text.trim()):(statusText.textContent="NUK DËGJOVA",addMessage("Nuk degjova asgje. Provo perseri.","jarvis"))}catch(e){console.error("STT error:",e),hideOverlay(),statusText.textContent="GABIM"}}
async function speak(t){if(!t)return;isSpeaking=!0,statusText.textContent="PO FLAS...";try{const r=await fetch("/api/text-to-speech",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({text:t})}),d=await r.json();if(d.audio&&d.audio.length>0){const s=new Uint8Array(d.audio),b=new Blob([s],{type:"audio/mpeg"}),u=URL.createObjectURL(b),a=new Audio(u);a.onend=()=>{isSpeaking=!1,URL.revokeObjectURL(u),statusText.textContent="ONLINE"},a.onerror=()=>{isSpeaking=!1,URL.revokeObjectURL(u),fallbackSpeak(t)},await a.play()}else fallbackSpeak(t)}catch{fallbackSpeak(t)}}
function fallbackSpeak(t){if(!("speechSynthesis"in window))return isSpeaking=!1,void(statusText.textContent="ONLINE");window.speechSynthesis.cancel();const e=new SpeechSynthesisUtterance(t.replace(/[*_`#]/g,""));e.lang="sq-AL",e.onend=()=>{isSpeaking=!1,statusText.textContent="ONLINE"},window.speechSynthesis.speak(e)}
function addMessage(t,s){const m=document.createElement("div");m.className="m "+s;const a=document.createElement("div");a.className="av",a.textContent="jarvis"===s?"J":"U";const b=document.createElement("div");b.className="b",b.textContent=t,m.appendChild(a),m.appendChild(b),chatArea.appendChild(m),chatArea.scrollTop=chatArea.scrollHeight}
function addTypingIndicator(){const m=document.createElement("div");m.className="m jarvis",m.id="typing";const a=document.createElement("div");a.className="av",a.textContent="J";const i=document.createElement("div");i.className="b typ",i.innerHTML="<span></span><span></span><span></span>",m.appendChild(a),m.appendChild(i),chatArea.appendChild(m),chatArea.scrollTop=chatArea.scrollHeight}
function removeTypingIndicator(){document.getElementById("typing")?.remove()}
async function sendMessage(t){if(!t.trim())return;/^(hej bylbyl|hej bilbyl|hej makrella|oj makrella|hej bir)/i.test(t.trim())?(addMessage(t,"user"),addMessage("Po dëgjoj! Flit tash...","jarvis"),recording||toggleMic()):(addMessage(t,"user"),history.push({role:"user",content:t}),userInput.value="",addTypingIndicator(),statusText.textContent="PO MENDOJ...",try{const r=await fetch("/api/chat",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({message:t,history:history.slice(-20)})}),d=await r.json();removeTypingIndicator();const p=d.reply||"Gabim.";addMessage(p,"jarvis"),history.push({role:"assistant",content:p}),await speak(p)}catch{removeTypingIndicator(),addMessage("Gabim lidhjeje.","jarvis"),statusText.textContent="GABIM"})}
wakeBtn.addEventListener("click",toggleMic);sendBtn.addEventListener("click",()=>sendMessage(userInput.value));userInput.addEventListener("keydown",e=>{"Enter"===e.key&&sendMessage(userInput.value)});voiceOverlay.addEventListener("click",e=>{"overlayClose"===e.target.id&&recording&&stopRecording()});
